// starts at 1
module.exports.schools = ['Physical', 'Holy', 'Holystrike', 'Fire',
                'Flamestrike', 'Holyfire', '', 'Nature',
                'Stormstrike', 'Holystorm', '', 'Firestorm',
                '', '', '', 'Frost',
                'Froststrike', 'Holyfrost', '', 'Frostfire',
                '', '', '', 'Froststorm',
                '', '', '', 'Elemental',
                '', '', '', 'Shadow',
                'Shadowstrike', 'Twilight', '', 'Shadowflame',
                '', '', '', 'Plague',
                '', '', '', '',
                '', '', '', 'Shadowfrost',
                '', '', '', '',
                '', '', '', '',
                '', '', '', '',
                '', '', '', 'Arcane',
                'Spellstrike', 'Divine', '', 'Spellfire',
                '', '', '', 'Astral',
                '', '', '', '',
                '', '', '', 'Spellfrost',
                '', '', '', '',
                '', '', '', '',
                '', '', '', '',
                '', '', '', 'Spellshadow',
                '', '', '', '',
                '', '', '', '',
                '', '', '', '',
                '', '', '', '',
                '', '', '', '',
                '', '', '', '',
                '', '', '', 'Chromatic (Chaos)',
                '', 'Magic', 'Chaos'
              ]

// starts at -2
module.exports.powers = ['Health', '', 'Mana', 'Rage', 'Focus', 'Energy', '', 'Runes', 'Runic Power']
